language: cpp
sudo: required
dist: xenial

compiler:
    - gcc
    - clang

env:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

cache:
  directories:
    boost-cache

script:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y ninja g++-8
    - mkdir build.tmp && cd build.tmp
    - 'if [ "$CXX" = "g++" ]; then export CC=gcc-8; export CXX=g++-8; fi'
    - git clone https://github.com/KayEss/fost-boost.git
    - git clone https://github.com/KayEss/fost-crypto.git
    - git clone https://github.com/KayEss/f5-cord.git
    - git clone https://github.com/KayEss/f5-threading.git
    - ln -s ../../boost-cache fost-boost/boost
    - cp ../.travis.CMakeLists.txt CMakeLists.txt
    - cmake . -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -G Ninja
    - ninja
    - ninja check

# Because gcc 7.x has a broken variant implementation, clang won't work
matrix:
    allow_failures:
        - compiler: clang
