version: 2.1

executors:
  clang:
    docker:
    - image: fost/circleci
    environment:
      CC: clang
      CXX: clang++
  gcc:
    docker:
    - image: fost/circleci
    environment:
      CC: gcc-10
      CXX: g++-10

jobs:
  build:
    parameters:
      compiler:
        type: executor
      variant:
        type: string
    executor: << parameters.compiler >>
    steps:
      - checkout
      - run:
          name: cmake
          environment:
            CMAKE_BUILD_TYPE: << parameters.variant >>
          command: cmake -G Ninja -S . -B .circleci
      - run:
          name: ninja
          command: ninja -C .circleci
      - run:
          name: check tests
          command: ninja -C .circleci check

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              compiler: [gcc, clang]
              variant: [Debug, Release]
